# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import Orders_pb2 as Orders__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in Orders_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrderbookServiceStub(object):
    """OrderbookService provides operations for managing orders in a financial trading system.
    This service supports both limit orders and market orders with various order types.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddOrder = channel.unary_unary(
                '/OrderbookService/AddOrder',
                request_serializer=Orders__pb2.AddOrderRequest.SerializeToString,
                response_deserializer=Orders__pb2.AddOrderResponse.FromString,
                _registered_method=True)
        self.AddMarketOrder = channel.unary_unary(
                '/OrderbookService/AddMarketOrder',
                request_serializer=Orders__pb2.AddMarketOrderRequest.SerializeToString,
                response_deserializer=Orders__pb2.AddOrderResponse.FromString,
                _registered_method=True)
        self.CancelOrder = channel.unary_unary(
                '/OrderbookService/CancelOrder',
                request_serializer=Orders__pb2.CancelOrderRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class OrderbookServiceServicer(object):
    """OrderbookService provides operations for managing orders in a financial trading system.
    This service supports both limit orders and market orders with various order types.
    """

    def AddOrder(self, request, context):
        """AddOrder places a new limit order with a specified price.
        The order will be added to the order book and matched according to the specified order type.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddMarketOrder(self, request, context):
        """AddMarketOrder places a new market order.
        Market orders are executed immediately at the best available price in the market.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOrder(self, request, context):
        """CancelOrder removes an existing order from the order book.
        The order to be cancelled is identified by its unique order ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderbookServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.AddOrder,
                    request_deserializer=Orders__pb2.AddOrderRequest.FromString,
                    response_serializer=Orders__pb2.AddOrderResponse.SerializeToString,
            ),
            'AddMarketOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.AddMarketOrder,
                    request_deserializer=Orders__pb2.AddMarketOrderRequest.FromString,
                    response_serializer=Orders__pb2.AddOrderResponse.SerializeToString,
            ),
            'CancelOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOrder,
                    request_deserializer=Orders__pb2.CancelOrderRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'OrderbookService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('OrderbookService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrderbookService(object):
    """OrderbookService provides operations for managing orders in a financial trading system.
    This service supports both limit orders and market orders with various order types.
    """

    @staticmethod
    def AddOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/OrderbookService/AddOrder',
            Orders__pb2.AddOrderRequest.SerializeToString,
            Orders__pb2.AddOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddMarketOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/OrderbookService/AddMarketOrder',
            Orders__pb2.AddMarketOrderRequest.SerializeToString,
            Orders__pb2.AddOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/OrderbookService/CancelOrder',
            Orders__pb2.CancelOrderRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
